In [45]:
%reload_kedro

[02/04/25 21:32:13] INFO     Resolved project path as: /Users/sharkovgrigory/code/fraud_detection.  ]8;id=802839;file:///Users/sharkovgrigory/miniconda3/envs/gnn_test/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=579402;file:///Users/sharkovgrigory/miniconda3/envs/gnn_test/lib/python3.12/site-packages/kedro/ipython/__init__.py#178\178]8;;\
                             To set a different path, run '%reload_kedro <project_root>'

                    INFO     Kedro project fraud_detection                                          ]8;id=175631;file:///Users/sharkovgrigory/miniconda3/envs/gnn_test/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=465985;file:///Users/sharkovgrigory/miniconda3/envs/gnn_test/lib/python3.12/site-packages/kedro/ipython/__init__.py#144\144]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=169840;file:///Users/sharkovgrigory/miniconda3/envs/gnn_test/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=39212;file:///Users/sharkovgrigory/miniconda3/envs/gnn_test/lib/python3.12/site-packages/kedro/ipython/__init__.py#145\145]8;;\
                             'pipelines'

                    INFO     Registered line magic 'run_viz'                                        ]8;id=254017;file:///Users/sharkovgrigory/miniconda3/envs/gnn_test/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=406051;file:///Users/sharkovgrigory/miniconda3/envs/gnn_test/lib/python3.12/site-packages/kedro/ipython/__init__.py#151\151]8;;\

In [46]:
dataset = catalog.load("raw_data")

                    INFO     Loading data from raw_data (PickleDataset)...                      ]8;id=427139;file:///Users/sharkovgrigory/miniconda3/envs/gnn_test/lib/python3.12/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=686493;file:///Users/sharkovgrigory/miniconda3/envs/gnn_test/lib/python3.12/site-packages/kedro/io/data_catalog.py#389\389]8;;\

In [47]:
dataset

Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708])

In [48]:
train_data = catalog.load("processed_data")
train_data

                    INFO     Loading data from processed_data (PickleDataset)...                ]8;id=181395;file:///Users/sharkovgrigory/miniconda3/envs/gnn_test/lib/python3.12/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=625490;file:///Users/sharkovgrigory/miniconda3/envs/gnn_test/lib/python3.12/site-packages/kedro/io/data_catalog.py#389\389]8;;\

Data(x=[203769, 166], edge_index=[2, 234355], y=[203769], train_mask=[203769], val_mask=[203769], test_mask=[203769], known_mask=[203769])

In [49]:
train_data.y

tensor([2, 2, 2,  ..., 0, 2, 2])

In [50]:
train_data.train_mask

tensor([False, False, False,  ..., False, False, False])

In [53]:
processed_data = catalog.load("processed_data")

[02/04/25 21:32:39] INFO     Loading data from processed_data (PickleDataset)...                ]8;id=430623;file:///Users/sharkovgrigory/miniconda3/envs/gnn_test/lib/python3.12/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=655084;file:///Users/sharkovgrigory/miniconda3/envs/gnn_test/lib/python3.12/site-packages/kedro/io/data_catalog.py#389\389]8;;\

In [54]:
processed_data

Data(x=[203769, 166], edge_index=[2, 234355], y=[203769], train_mask=[203769], val_mask=[203769], test_mask=[203769], known_mask=[203769])

In [55]:
processed_data.x[processed_data.train_mask]

tensor([[ 1.0000e+00,  1.6305e-01,  1.9638e+00,  ...,  6.7780e-01,
         -1.2061e-01, -1.1979e-01],
        [ 1.0000e+00, -5.0271e-03,  5.7894e-01,  ...,  3.3321e-01,
         -1.2061e-01, -1.1979e-01],
        [ 1.0000e+00, -1.4785e-01, -1.8467e-01,  ..., -9.7524e-02,
         -1.2061e-01, -1.1979e-01],
        ...,
        [ 4.9000e+01, -1.5929e-01, -3.7276e-02,  ...,  3.7073e+00,
         -1.3905e+00, -1.2140e+00],
        [ 4.9000e+01, -1.7296e-01, -1.2657e-01,  ...,  7.9141e+00,
         -1.2061e-01, -1.1979e-01],
        [ 4.9000e+01, -1.7041e-01, -7.8164e-02,  ..., -9.7524e-02,
         -1.2061e-01, -1.1979e-01]])

In [56]:
raw_data = catalog.load("raw_data")

[02/04/25 21:32:44] INFO     Loading data from raw_data (PickleDataset)...                      ]8;id=813662;file:///Users/sharkovgrigory/miniconda3/envs/gnn_test/lib/python3.12/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=81111;file:///Users/sharkovgrigory/miniconda3/envs/gnn_test/lib/python3.12/site-packages/kedro/io/data_catalog.py#389\389]8;;\

In [57]:
raw_labels = catalog.load("raw_labels")

[02/04/25 21:32:45] INFO     Loading data from raw_labels (CSVDataset)...                       ]8;id=808950;file:///Users/sharkovgrigory/miniconda3/envs/gnn_test/lib/python3.12/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=309018;file:///Users/sharkovgrigory/miniconda3/envs/gnn_test/lib/python3.12/site-packages/kedro/io/data_catalog.py#389\389]8;;\

In [58]:
raw_labels

             txId    class
0       230425980  unknown
1         5530458  unknown
2       232022460  unknown
3       232438397        2
4       230460314  unknown
...           ...      ...
203764  173077460  unknown
203765  158577750  unknown
203766  158375402        1
203767  158654197  unknown
203768  157597225  unknown

[203769 rows x 2 columns]

In [59]:
raw_features = catalog.load("raw_features")

[02/04/25 21:32:47] INFO     Loading data from raw_features (CSVDataset)...                     ]8;id=342114;file:///Users/sharkovgrigory/miniconda3/envs/gnn_test/lib/python3.12/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=57907;file:///Users/sharkovgrigory/miniconda3/envs/gnn_test/lib/python3.12/site-packages/kedro/io/data_catalog.py#389\389]8;;\

In [60]:
raw_features

,0,1,2,3,4,5,6,7,8,9,...,157,158,159,160,161,162,163,164,165,166
0,230425980,1,-0.171469,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.162097,...,-0.562153,-0.600999,1.461330,1.461369,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792
1,5530458,1,-0.171484,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.162112,...,0.947382,0.673103,-0.979074,-0.978556,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792
2,232022460,1,-0.172107,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.162749,...,0.670883,0.439728,-0.979074,-0.978556,-0.098889,-0.106715,-0.131155,-0.183671,-0.120613,-0.119792
3,232438397,1,0.163054,1.963790,-0.646376,12.409294,-0.063725,9.782742,12.414558,-0.163645,...,-0.577099,-0.613614,0.241128,0.241406,1.072793,0.085530,-0.131155,0.677799,-0.120613,-0.119792
4,230460314,1,1.011523,-0.081127,-1.201369,1.153668,0.333276,1.312656,-0.061584,-0.163523,...,-0.511871,-0.400422,0.517257,0.579382,0.018279,0.277775,0.326394,1.293750,0.178136,0.179117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203764,173077460,49,-0.145771,-0.163752,0.463609,-0.121970,-0.043875,-0.113002,-0.061584,-0.135803,...,-0.577099,-0.613614,0.241128,0.241406,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792
203765,158577750,49,-0.165920,-0.123607,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.156418,...,0.162722,0.010822,1.461330,1.461369,-0.098889,-0.087490,-0.084674,-0.140597,-1.760926,-1.760984
203766,158375402,49,-0.172014,-0.078182,1.018602,0.028105,-0.043875,0.054722,-0.061584,-0.163626,...,1.261246,1.985050,1.461330,1.461369,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792
203767,158654197,49,-0.172842,-0.176622,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.163501,...,-0.397749,-0.411776,1.461330,1.461369,-0.098889,-0.087490,-0.084674,-0.140597,1.519700,1.521399
203768,157597225,49,-0.012037,-0.132276,0.463609,-0.121970,-0.043875,-0.113002,-0.061584,0.001027,...,-0.577099,-0.613614,0.241128,0.241406,-0.098889,-0.087490,-0.084674,-0.140597,1.519700,1.521399

In [61]:
raw_data

Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708])

In [62]:
processed_data

Data(x=[203769, 166], edge_index=[2, 234355], y=[203769], train_mask=[203769], val_mask=[203769], test_mask=[203769], known_mask=[203769])

In [63]:
import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv


class GCN(torch.nn.Module):
    def __init__(self, num_features: int, hidden_size: int, num_classes: int) -> None:
        super().__init__()
        self.conv1 = GCNConv(num_features, hidden_size)
        self.conv2 = GCNConv(hidden_size, num_classes)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index

        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, p=0.5, training=self.training)

        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)

In [64]:
import logging

DEVICE_MAPPING = {
    "gpu": torch.cuda,
    "mps": torch.backends.mps,
}

logger = logging.getLogger(__name__)

def get_torch_device() -> torch.device:
    """gets the best performant device (CPU or MPS)"""
    for device_name, device in DEVICE_MAPPING.items():
        if device.is_available():
            logger.info(f"Using {device_name} device")
            return torch.device(device_name)

    logger.info(f"Using {device_name} device")
    return torch.device("cpu")

device = get_torch_device()

model = GCN(
    num_features=train_data.num_node_features,
    hidden_size=20,
    num_classes=torch.unique(train_data.y).numel(),
).to(device)

In [66]:
model(train_data.to(device))

tensor([[-0.9473, -0.6077, -2.6940],
        [-0.5406, -1.0965, -2.4817],
        [-0.8950, -0.8724, -1.7519],
        ...,
        [-0.1305, -2.1058, -7.4149],
        [-0.1083, -2.5565, -3.6849],
        [-4.1899, -3.0426, -0.0649]], device='mps:0',
       grad_fn=<LogSoftmaxBackward0>)